### PR TITLE
Configuration File Support

### PR DESCRIPTION
**Pull request by EvanJGunn**
Merging of Zed and Zhaoyu's work on the Configuration files with my work on the class for configuration management, as well as the class for regular expression management.

- Improved regular expressions for Email and URL set as default in package.json
- Slightly altered the package.json schema for regexes to support an array of them.
- Created ConfigManager class to manage all access to the configuration files.
- Moved TypedRegex (renamed from NamedRegex) to its own typescript file.
- Modified RegexManager.ts to use the new ConfigManager class to get data from package.json.

### CODE REVIEW

**Review by wu000168 — COMMENTED** [review]
Should API and/or common data model configs be implemented before merging?

**Comment by EvanJGunn** [comment]
Well I am using the API schema you and Zhaoyu set up, however nothing related to API/Common data model is hard coded in this merge. This merge currently only pulls data from package.json for the regular expressions. I thought we should merge this before demonstrating to the Target team, as it shows the way in which we pull data from settings.

**Review by wu000168 — APPROVED** [review]
In that case the RegEx part looks fine to me then

**Review by PrateekVachher — APPROVED** [review]
Looks good to me

**Pull request merged**
